"""initial migration

Revision ID: 49394144a1db
Revises: 
Create Date: 2024-02-06 11:53:40.805317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49394144a1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign')
    # ### end Alembic commands ###
